In [8]:
import pandas as pd
import os

pd.set_option("display.max_columns", 500)
df = pd.read_csv('mta/turnstile_210102.txt')
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2020,03:00:00,REGULAR,7508509,2557569
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2020,07:00:00,REGULAR,7508511,2557581
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2020,11:00:00,REGULAR,7508531,2557636
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2020,15:00:00,REGULAR,7508610,2557667
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/26/2020,19:00:00,REGULAR,7508767,2557689
...,...,...,...,...,...,...,...,...,...,...,...
210428,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2021,04:00:00,REGULAR,5554,541
210429,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2021,08:00:00,REGULAR,5554,541
210430,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2021,12:00:00,REGULAR,5554,541
210431,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2021,16:00:00,REGULAR,5554,541
210432,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/01/2021,20:00:00,REGULAR,5554,541

In [9]:
def mta_to_df():
    filenames = os.listdir('mta')
    data = pd.DataFrame()

    for file in filenames:
        df = pd.read_csv('mta/' + file)
        data = pd.concat([data, df])
    return data

In [ ]:
get_files()